package com.example.laba_5_sem_2_javafx.enums;

public enum Manufacture {
    AUDI, ACURA, ALFA_ROMEO, ASTON_MARTIN, BENTLEY, BYD, BMW, BUGATTI, CADILLAC, CHEVROLET, CITROEN,
    DODGE, FIAT, FORD, FERRARI, INFINITI, JAGUAR, JEEP, KIA, LAMBORGINI, LEXUS, MAYBACH, MERCEDES,
    NISSAN, OPEL, PEUGEOT, PORSHE, RENAULT, SKODA, TOYOTA, ROLLS_ROYCE, TESLA, VOLVO,VOLKSWAGEN
}
